# Site settings
title: Prathmesh Savale's Blog
email: prathmesh.savale@gmail.com
description: "All things Data Science"
baseurl: ""
url: "http://praths007.github.io"
twitter_username: praths_007
github_username:  praths007
linkedin_username: prathmeshsavale

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
